#!/opt/perl/bin/perl
# Name: check_informix
# Description: Check Informix Logs
# Date: 2012-10-12
# Version: 1.0
# Platform: Solaris 10
# Author: Luke Simmons

use Getopt::Long;
use lib qw(/opt/plugins);
use lib qw(/opt/informix/scripts);
use Informix;
use utils qw($TIMEOUT %ERRORS);
use strict;

my $warning;
my $critical;
my $help;
my $usage;
my $TIMEOUT;
my $name;
my $nrpe_name;

# Name used for the output in nrpe
$name = "Check IDS logs";
$nrpe_name = "check_ids_logs";

# Parameters for nrpe
my $parameter = "logs_not_backed";

# Timeout in seconds
$TIMEOUT = 30;

# Informix variables
my $INFORMIXDIR='';
my $INFORMIXSERVER="";

# Authentication
my $username = "";
my $password = "";

# Options
GetOptions(
		"critical:i" => \$critical,
		"warning:i" => \$warning,
		"help" => \$help,
		"usage" => \$usage
);

help() if defined($help) || defined($usage);

$ENV{'PATH'} = "/bin:/sbin:/usr/bin:/opt/csw/bin:$INFORMIXDIR/bin";
$ENV{'INFORMIXSERVER'} = $INFORMIXSERVER;

sub help {
	print "Usage:\n";	
	print "\t$nrpe_name\n";
	print "Example\n";
	print "\t$nrpe_name -c <critical> -w <warning>\n";
	print "$critical\n";
	print "$warning\n";
	exit 0;
}

# Initiate object
my $ids = new Informix("sysmaster",$INFORMIXSERVER,$username,$password);
$ids->connect($username,$password);

# The command(s) we're going to run / object we're going to call
my $result = $ids->checkLogs();
$result =~ s/^\s+//g;
$result =~ s/^\s+//g;

# Timeout handler used 
$SIG{'ALRM'} = sub {
	print "Plugin timed out after $TIMEOUT seconds - CRITICAL\n";
	exit($ERRORS{'CRITICAL'});
};

# Install timeout handler, so that the plugin does not hang indefinitely.
alarm($TIMEOUT);

if ( defined $critical ) {

	if ($result eq "") {
		print "\u$name - CRITICAL - one or more processes have died unexpectedly\n";
		exit($ERRORS{'CRITICAL'});
	} elsif ($result >= $critical) {
		print "\u$name - CRITICAL | $parameter=$result\n";
		exit($ERRORS{'CRITICAL'});
	} elsif ($result >= $warning) {
		print "\u$name - WARNING | $parameter=$result\n";
		exit($ERRORS{'WARNING'});
	}

}

print "\u$name - OK | $parameter=$result\n";
