#!/opt/perl/bin/perl
# Name: check_informix
# Description: Check Informix Logs
# Date: 2012-10-12
# Version: 1.0
# Platform: Solaris 10
# Author: Luke Simmons

use lib qw(/opt/plugins);
use lib qw(/opt/informix/scripts);
use Informix;
use utils qw($TIMEOUT %ERRORS);
use Getopt::Long;
use strict;

my $warning;
my $critical;
my $help;
my $usage;
my $TIMEOUT;
my $name;
my $parameter;

# Name used for the output in nrpe
$name = "Check IDS status";

# Parameters for nrpe

# Timeout in seconds
$TIMEOUT = 30;

# Informix variables
my $INFORMIXDIR='';
my $INFORMIXSERVER="";

# Authentication
my $username = "";
my $password = "";

# Options
GetOptions(
		"critical:i" => \$critical,
		"warning:i" => \$warning,
		"help" => \$help,
		"usage" => \$usage
);

help() if defined($help) || defined($usage);

$ENV{'PATH'} = "/bin:/sbin:/usr/bin:/opt/csw/bin:$INFORMIXDIR/bin";
$ENV{'INFORMIXSERVER'} = $INFORMIXSERVER;

sub help {
	print "Usage:\n";	
	print "\t$name\n";
	print "Example\n";
	if (defined $critical) {
		print "\t$name -c $critical -w $warning\n";
	} else {
		print "\t$name\n";
	}
	exit 0;
}

# Initiate object
my $ids = new Informix("sysmaster",$INFORMIXSERVER,$username,$password);
$ids->connect($username,$password);

# The command(s) we're going to run / object we're going to call
my $result = $ids->checkStatus();

if ($result != "5") {
	$result = 1;
} else {
	$result = 0;
}

# Timeout handler used 
$SIG{'ALRM'} = sub {
	print "Plugin timed out after $TIMEOUT seconds - CRITICAL\n";
	exit($ERRORS{'CRITICAL'});
};

# Install timeout handler, so that the plugin does not hang indefinitely.
alarm($TIMEOUT);

if ( defined $critical ) {
	if (defined $parameter) {
		if ($result eq "") {
			print "\u$name - CRITICAL - one or more processes have died unexpectedly\n";
			exit($ERRORS{'CRITICAL'});
		} elsif ($result >= $critical) {
			print "\u$name - CRITICAL | $parameter=$result\n";
			exit($ERRORS{'CRITICAL'});
		} elsif ($result >= $warning) {
			print "\u$name - WARNING | $parameter=$result\n";
			exit($ERRORS{'WARNING'});
		}
	} else {
		if ($result eq "") {
			print "\u$name - CRITICAL - one or more processes have died unexpectedly\n";
			exit($ERRORS{'CRITICAL'});
		} elsif ($result >= $critical) {
			print "\u$name - CRITICAL\n";
			exit($ERRORS{'CRITICAL'});
		} elsif ($result >= $warning) {
			print "\u$name - WARNING\n";
			exit($ERRORS{'WARNING'});
		}
	} 
}

if (defined $parameter) {
	print "\u$name - OK | $parameter=$result\n";
} else {
	print "\u$name - OK\n";
}
